### ISSUE TITLE
Why aren't .hh files included via --ffi?

### ISSUE THREAD

**Issue by kasbah** [andyarvanitis/purescript-native#10]
Just a bit confusing as I switch between `psc` and `pcc`.

**Comment by andyarvanitis** [comment]
Partly because you might need corresponding `.cc` files as well (it will automatically look for both), and partly it's for easily using a simple `makefile`. I'm open to changing it at some point, especially as more time is spent on support tools.

**Comment by kasbah** [comment]
Ah ok, its making my makefile that can switch between `psc` and `pcc` a bit uglier at the moment, that is all.

**Comment by andyarvanitis** [comment]
`pcc` should at least be ignoring the `--ffi` for now, if that helps.
