### ISSUE TITLE
Which pure11/purescript-native repo to link to?

### ISSUE THREAD

**Issue by dbohdan** [andyarvanitis/purescript-native#11]
Hi! I maintain a [list of open source compilers that generate C or C++ code](https://github.com/dbohdan/compilers-targeting-c). Which link should I give for PureScript's native target, https://github.com/andyarvanitis/purescript-native or https://github.com/pure11/pure11? (And should I call it "pure11"?)

**Comment by andyarvanitis** [comment]
Either is fine -- I'm keeping the two of them in sync these days. Either name is fine as well, but I'm leaning toward the "purescript-native" branding going forward.

**Comment by dbohdan** [comment]
All right, ["purescript-native" it is](https://github.com/dbohdan/compilers-targeting-c/commit/5ed5a34b43fd2f4e4e9d8920a882fac27328118f). Thanks.
