### ISSUE TITLE
cannot compile a simple example (Windows)

### ISSUE THREAD

**Issue by jellyr** [andyarvanitis/purescript-native#15]
## I wrote a simple program as follows:

  module Main where
  import Prelude
  import Control.Monad.Eff.Console (log, logShow)

  fib :: Int -> Int
  fib 0 = 0
  fib 1 = 1
  fib n = fib (n - 2) + fib (n - 1)

  main = do
    log "Here's the result of fib 10:"
    logShow (fib 10)

## I build it use pulp build , and it generated as follows

// Generated by pcc version 0.10.7

include "Main/Main.hh"

namespace Main {
  using namespace PureScript;
  using namespace Prelude;
  using namespace Control_Monad_Eff_Console;
  using namespace Data_Semiring;
  using namespace Data_Ring;
  using namespace Control_Bind;
  using namespace Control_Monad_Eff;
  using namespace Data_Show;

  
  auto fib(int v) -> int {
    switch (static_cast<int>(v)) {
      case 0: return 0;
      case 1: return 1;
    };
    return fib(v - 2) + fib(v - 1);
  };
  auto main() -> any {
    Control_Monad_Eff_Console::log("Here\'s the result of fib 10:")();
    return Control_Monad_Eff_Console::logShow(Data_Show::showInt, fib(10))();
  };
}

auto main(int, char *[]) -> int {
  using namespace Main;
  INITIALIZE_GC();
  Main::main();
  return 0;
};

## I got these errors
"Creating" output/Control.Monad/Monad.o
In file included from output/Data.Unit/Unit.hh:6:0,
                 from output/Data.Functor/Functor.hh:7,
                 from output/Control.Apply/Apply.hh:6,
                 from output/Control.Applicative/Applicative.hh:6,
                 from output/Control.Monad/Monad.hh:6,
                 from output/Control.Monad/Monad.cc:3:
output/Data.Show/Show.hh: In function 'PureScript::any Data_Show::$showCharImpl(const PureScript::any&)':
output/Data.Show/Show.hh:49:27: error: 'showCharImpl' was not declared in this scope
     return showCharImpl($6);
                           ^
output/Data.Show/Show.hh: In function 'PureScript::any Data_Show::$showIntImpl(const PureScript::any&)':
output/Data.Show/Show.hh:52:26: error: 'showIntImpl' was not declared in this scope
     return showIntImpl($7);
                          ^
output/Data.Show/Show.hh: In function 'PureScript::any Data_Show::$showNumberImpl(const PureScript::any&)':
output/Data.Show/Show.hh:55:29: error: 'showNumberImpl' was not declared in this scope
     return showNumberImpl($8);
                             ^
output/Data.Show/Show.hh: In function 'PureScript::any Data_Show::$showStringImpl(const PureScript::any&)':
output/Data.Show/Show.hh:58:29: error: 'showStringImpl' was not declared in this scope
     return showStringImpl($9);
                             ^
At global scope:
cc1plus.exe: warning: unrecognized command line option '-Wno-logical-op-parentheses'
Makefile:161: recipe for target 'output/Control.Monad/Monad.o' failed
make[1]: *** [output/Control.Monad/Monad.o] Error 1
make[1]: Leaving directory 'E:/hs/pur11'
Makefile:104: recipe for target 'release' failed
make: *** [release] Error 2
## here is the Show.hh
// Generated by pcc version 0.10.7
#ifndef Data_Show_HH
#define Data_Show_HH

#include "PureScript/PureScript.hh"
#include "Show_ffi.hh"

namespace Data_Show {
  using namespace PureScript;

  
  namespace ctor {
    enum : int { _ };
  }
  
  struct Show {
    enum { show };
  };
  auto showString(any::as_thunk) -> const any&;
  auto showNumber(any::as_thunk) -> const any&;
  auto showInt(any::as_thunk) -> const any&;
  auto showChar(any::as_thunk) -> const any&;
  auto showBoolean(any::as_thunk) -> const any&;
  
  auto showArray(const any&) -> any;
  auto $showArrayImpl(const any&) -> any;
  
  /**
   *  | The `Show` type class represents those types which can be converted into
   *  | a human-readable `String` representation.
   *  |
   *  | While not required, it is recommended that for any expression `x`, the
   *  | string `show x` be executable PureScript code which evaluates to the same
   *  | value as the expression `x`.
   */
  
  inline auto $show(const any& dict) -> any {
    return dict::get<Show::show>(dict);
  };
  inline auto show(const any& dict, const any& $3) -> any {
    return dict::get<Show::show>(dict)($3);
  };
  
  inline auto $showArray(const any& dictShow) -> any {
    return showArray(dictShow);
  };
  inline auto $showCharImpl(const any& $6) -> any {
    return showCharImpl($6);
  };
  inline auto $showIntImpl(const any& $7) -> any {
    return showIntImpl($7);
  };
  inline auto $showNumberImpl(const any& $8) -> any {
    return showNumberImpl($8);
  };
  inline auto $showStringImpl(const any& $9) -> any {
    return showStringImpl($9);
  };
}

#endif // Data_Show_HH
`

## here is the show.cc
`// Generated by pcc version 0.10.7

#include "Data.Show/Show.hh"

DEFINE_SYMBOL(show)

namespace Data_Show {
  using namespace PureScript;

  auto showString(any::as_thunk) -> const any& {
    static const any the_value = dict::make(
      { SYM(show), $showStringImpl }
    );
    return the_value;
  };
  auto showNumber(any::as_thunk) -> const any& {
    static const any the_value = dict::make(
      { SYM(show), $showNumberImpl }
    );
    return the_value;
  };
  auto showInt(any::as_thunk) -> const any& {
    static const any the_value = dict::make(
      { SYM(show), $showIntImpl }
    );
    return the_value;
  };
  auto showChar(any::as_thunk) -> const any& {
    static const any the_value = dict::make(
      { SYM(show), $showCharImpl }
    );
    return the_value;
  };
  auto showBoolean(any::as_thunk) -> const any& {
    static const any the_value = dict::make(
      { SYM(show), [](const any& v) -> any {
        if (v) {
          return any("true");
        } else {
          return any("false");
        };
      } }
    );
    return the_value;
  };
  
  auto showArray(const any& dictShow) -> any {
    return dict::make(
      { SYM(show), $showArrayImpl($show(dictShow)) }
    );
  };
  auto $showArrayImpl(const any& $4) -> any {
    return [=](const any& $5) -> any {
      return showArrayImpl($4, $5);
    };
  };
}

`
## my purescript-native sha version is 
  `0cab7d6cfbea0cd29ba0376da2139fea45383928`
## MAKE version is :
GNU Make 4.1
Built for i686-w64-mingw32

## GCC version is 
gcc (i686-posix-sjlj-rev1, Built by MinGW-W64 project) 6.3.0
Copyright (C) 2016 Free Software Foundation, Inc.`

## so, Did I do something wrong?   I also convert make file to visual studio 2015 project, I got the same error!

**Comment by andyarvanitis** [comment]
I haven't used pulp to build the C++ target, but it looks like it should be ok, as long as you end up with the standard results in the `output` directory and then use the default `Makefile` described here: https://github.com/pure11/pure11#getting-started. But can you try using those instructions instead (no `pulp`, just `make` for everything), and see how that goes? It looks to me like your include paths aren't there for some reason. See also http://andyarvanitis.com/hello-world-purescript-cpp/ (even though you're on Windows, but much of it still applies).

**Comment by andyarvanitis** [comment]
Actually, sorry, I was wrong, it doesn't look related to make paths -- I'm guessing you have the wrong versions of the packages, probably retrieved by `pulp`. Please try using `psc-package` (it's the "official" tool for the C++ backend) using either of those instructions I've linked, and let me know if you're still having problems.

**Comment by jellyr** [comment]
## Yes, you are right, I have  wrong versions of the packages!

psc-package  work fine, I use ./pcc first , and then psc-package update, then make.  And works fine .

I follow this article  [http://andyarvanitis.com/hello-world-purescript-cpp/ ](url) , and finally I got compiled sucessfully!!  And also got vs2015 compiled successful!!!  Thank you very much !!

The instructions are : 
## 1, install mingw : [http://iweb.dl.sourceforge.net/project/mingw-w64/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/installer/mingw-w64-install.exe](url)
        chosse  version 6.3.0
                architecture i686
                threads posix
                exception  sjlj
                build revision 1
## 2,createWorkingDir,  "workDir" for example.
## 3, mkdir src 
## 4,copy some Main.purs to src 
for eaxmple, the content  of Main.purs is 
        module Main where

        import Prelude
        import Control.Monad.Eff.Console (log, logShow)

        main = do
          logShow(2)

## 5, ./pcc
###       you can get pcc.exe as follows 
        git clone https://github.com/andyarvanitis/purescript-native.git
        stack setup
        stack build 
then you should find pcc.exe 
or you can download all exe you needed in 
[https://github.com/jellyr/ConvertPure11ToVS2015/releases/tag/1.0](url) for pcc.exe and vbs
[https://github.com/purescript/purescript/releases](url)   purescript exes
make sure these exes is in your system path!!
## 6, make 
note: The make file won't work on my current mingw on windows 10. It report errors as follows :
$ make
      Makefile:26: extraneous text after 'ifeq' directive
      Makefile:92: *** missing 'endif'.  Stop.
###       Then I change 
      ifeq ($(GC),yes)
        override CXXFLAGS += -DUSE_GC
        override LDFLAGS += -lgc
      endif
###       to 

      ifeq ($(GC),yes)
        override CXXFLAGS += -DUSE_GC
      endif

      ifeq ($(GC),yes)
        override LDFLAGS += -lgc
      endif

###       The make will work fine!

###      one more thing to note
   @mkdir -p $(BIN_DIR)  
   the windows mkdir cmd do not support -p arg,  excute mingw-w64.bat as your terminal.
## 7,now, you should see  "main.exe" in your output\bin dir!
   now,let's convert it to vs2015 project,  *.vcxproj.
   download vbs from https://github.com/jellyr/ConvertPure11ToVS2015/blob/master/ConvertPure11ToVS2015.vbs
## 8, put the vbs to your working dir, the same path as your Makefile . 
   the architecture should look like 
   output
   -------Control.Applicative
   -------Control.Apply
   -------And so on
   src
   ---------Main.purs
   Makefile
   psc-package.json
   ConvertPure11ToVS2015.vbs
## 9, run  ConvertPure11ToVS2015.vbs
   you should see YourOwnProjectName.vcxproj in your output dir, 
   open it with VS2015, build it.
## 10, you should see an error . 
     Show_ffi.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: static class std::locale::id std::codecvt<char32_t,char,struct _Mbstatet>::id" (__imp_?id@?$codecvt@_UDU_Mbstatet@@@std@@2V0locale@2@A)
## 11,it is vs2015's bug. see [https://social.msdn.microsoft.com/Forums/vstudio/en-US/8f40dcd8-c67f-4eba-9134-a19b9178e481/vs-2015-rc-linker-stdcodecvt-error?forum=vcgeneral](url)  for detail.
open show_ffi.cc 
change 
 static std::wstring_convert<std::codecvt_utf8<char32_t>, char32_t> utf32conv;
to 
static std::wstring_convert<std::codecvt_utf8<wchar_t>, wchar_t> utf32conv;
## 12, Now, if every thing goes right, your should see 
1>  YourOwnProjectName.vcxproj -> E:\hs\pur11HelloWorld\output\Debug\YourOwnProjectName.exe
1>  YourOwnProjectName.vcxproj -> E:\hs\pur11HelloWorld\output\Debug\YourOwnProjectName.pdb (Full PDB)

# 13, cheer!!!!
for example, I want test Maybe Monad.

module Main where

import Prelude
import Control.Monad.Eff.Console (log, logShow)
import Data.Maybe


main = do
  logShow $ (Nothing::Maybe Int) >>= \x -> pure $x * 10
  logShow $ (Just 3::Maybe Int )  >>= \x -> pure $ x * 10



I can add , 
**maybe** to **psc-package.json**  and then run cmd **psc-package update**
or run command p**sc-package install maybe**
and then run **make** 
gcc will compile success , then run vbs as above instructions and compile use vs2015.  I it will success too!
great!!!  but It seems there's some other issues , I'll write on another thread.

**Comment by andyarvanitis** [comment]
Great! And thanks for the detailed notes. I haven't had any issues with mingw or VS2015 in the past, but I'll have a closer look at your notes and try it again soon.
