### ISSUE TITLE
libncurses5-dev required when building on ubuntu

### ISSUE THREAD

**Issue by Thimoteus** [andyarvanitis/purescript-native#17]
I've built the latest upstream PS compiler using stack, but running `stack install` for purescript-native results in

    configure: error: in `/tmp/stack31409/terminfo-0.4.0.2':
    configure: error: curses headers could not be found, so this package cannot be built
    See `config.log' for more details

installing `libncurses5-dev` solves the problem.

**Comment by andyarvanitis** [comment]
Tested new codebase with a fresh install of Ubuntu 18.04.1 and seems to build fine. Did not appear to need an explicit installation of any version of libncurses.
