### ISSUE TITLE
Move over to LLVM C++ API incrementally

### ISSUE THREAD

**Issue by Yzrsah** [andyarvanitis/purescript-native#24]
Hello,

We could move to LLVM by replacing small bits of functionality incrementally with calls to the native LLVM C++ API.

This approach has been used by various projects
Example here, https://www.youtube.com/watch?v=mbdXeRBbgDM

**Comment by bbarker** [comment]
Maybe I misunderstood the question, but I sort of like the idea of keeping the project compiler-independent. This gives a lot of potential flexibility, imo, for integrating PS into existing projects.

**Comment by andyarvanitis** [comment]
@bbarker That and debuggable code -- just use your favorite/required/platform-specific C++ build tools and source-level debugger(s). I thought it worth keeping the question here, since I get asked about it occasionally.
