### ISSUE TITLE
No matching function for call to ‘purescript::boxed::boxed()’.

### ISSUE THREAD

**Issue by lettier** [andyarvanitis/purescript-native#25]
Hello @andyarvanitis,

I believe removing this [line from the run time](https://github.com/andyarvanitis/purescript-native/commit/b18eb12359dadeda4ac02cb9e35fa15d7fbce8d0#diff-817099a16d2e5e67ea4389eb415d90b3L41) causes the following error.

```bash
In file included from output/src/purescript.h:23:0,
                 from output/src/Global/Global.h:6,
                 from output/src/Global/Global.cpp:2:
output/src/string_literal_dict.h: In instantiation of ‘T& string_literal_dict_t<T>::operator[](const char*) [with T = purescript::boxed]’:
output/src/purescript.h:97:52:   required from here
output/src/string_literal_dict.h:70:12: error: no matching function for call to ‘purescript::boxed::boxed()’
```

I don't believe this is specific to [purescript-globals](https://github.com/purescript/purescript-globals) but it could be. The compiler throws an error [here](https://github.com/andyarvanitis/purescript-native/blob/b18eb12359dadeda4ac02cb9e35fa15d7fbce8d0/runtime/string_literal_dict.h#L70).

Rolling back to the previous [commit](https://github.com/andyarvanitis/purescript-native/tree/421f9de78f34c57024750e8fbfe834970523143e) does resolve the issue.

Thanks!

:+1:

**Comment by andyarvanitis** [comment]
Ok, thanks, I'll revert that constructor removal and re-test. It's interesting that it's failing, as the test suite passed. Just so I know, could you tell me the C++ compiler and its version you're using? Thanks again for the report -- interested to see what you're working on.

**Comment by lettier** [comment]
Hello @andyarvanitis,

The error occurs with g++ 5.4.0. I had to build the project on Ubuntu 16.04 LTS to ensure greater compatibility with many other distributions. 

The error does _not_ occur with g++ 8.2.1.

I'm working on [Lambda Lantern](https://github.com/lettier/lambda-lantern)—a 3D game about functional programming patterns. 

:+1:

**Comment by andyarvanitis** [comment]
Ah, very good info, thanks. And your project looks very cool!

**Comment by andyarvanitis** [comment]
Updated, tested, and checked in, thanks.
