### ISSUE TITLE
Windows embedFile errors (utf?)

### ISSUE THREAD

**Issue by btrepp** [andyarvanitis/purescript-native#26]
On windows I had issues with the embedded runtime files becoming corrupted.
purescript.h was written out, but the compiler (clang) didn't like it.
string_literal_dict.h wasn't even able to be written to disk.

Copying the runtime files into the expected output/src directory then running make does get me a compile. (using clang+MSVC, though I had to target c++14 instead of 11).

This may be a similar issue to https://github.com/spacchetti/spago/pull/51

>  make clean && make
> Compiling Data.Symbol
> Compiling Record.Unsafe
> Compiling Type.Data.RowList
> Compiling Type.Data.Row
> Compiling Data.NaturalTransformation
> Compiling Control.Semigroupoid
> Compiling Data.Boolean
> Compiling Data.Show
> Compiling Control.Category
> Compiling Data.Unit
> Compiling Data.Void
> Compiling Data.HeytingAlgebra
> Compiling Data.Semiring
> Compiling Data.Semigroup
> Compiling Data.Ring
> Compiling Data.BooleanAlgebra
> Compiling Data.Eq
> Compiling Data.CommutativeRing
> Compiling Data.Ordering
> Compiling Data.EuclideanRing
> Compiling Data.Ord.Unsafe
> Compiling Data.Ord
> Compiling Data.DivisionRing
> Compiling Data.Field
> Compiling Data.Function
> Compiling Data.Monoid
> Compiling Data.Bounded
> Compiling Data.Functor
> Compiling Control.Apply
> Compiling Control.Applicative
> Compiling Control.Bind
> Compiling Control.Monad
> Compiling Prelude
> Compiling Effect
> Compiling Data.Semigroup.First
> Compiling Data.Monoid.Dual
> Compiling Data.Semigroup.Last
> Compiling Data.Monoid.Additive
> Compiling Data.Monoid.Conj
> Compiling Data.Monoid.Disj
> Compiling Data.Monoid.Multiplicative
> Compiling Data.Monoid.Endo
> Compiling Effect.Unsafe
> Compiling Effect.Class
> Compiling Effect.Uncurried
> Compiling Effect.Console
> Compiling Effect.Class.Console
> Compiling Main
> pscpp.exe: output\src\string_literal_dict.h: commitAndReleaseBuffer: invalid argument (invalid character)

**Comment by andyarvanitis** [comment]
Thanks for the report, I'll have a look. I don't recall having any problems when testing on Windows 10 and the latest Visual Studio -- with its default compiler, not clang, and not using `make`. I'll try some combinations.

**Comment by btrepp** [comment]
No problems. To clarify I think this is a problem with the haskell side and embedding files. The pscpp step that dumps out `string_literal_dict.h` fails as pscpp.exe fails to write the embedded content to disk. So it's failing before we even get to the C++ compilation step.

**Comment by andyarvanitis** [comment]
Ah, right, I wasn't thinking. Thanks.

**Comment by andyarvanitis** [comment]
Unfortunately, my code already does what spago did to fix the issue. I'll dig into it some more.

**Comment by andyarvanitis** [comment]
I'd like to find a programmatic solution to this, but for now it looks like you need to set your windows console to use UTF-8 before running the `pscpp` compiler. To do that, enter this on your active command prompt (once) before running a purescript-native build:

```
chcp 65001
```

**Comment by andyarvanitis** [comment]
Address in PR #31
