### ISSUE TITLE
Support for go modules?

### ISSUE THREAD

**Issue by pmahoney** [andyarvanitis/purescript-native#37]
I successfully built a "hello world" program following [the Getting Started guide](https://github.com/andyarvanitis/purescript-native/blob/golang/README-go.md).

However, I cannot build when using [go modules](https://github.com/golang/go/wiki/Modules).

For example, in my working directory, I have a `go.mod` containing `github.com/pmahoney/example`. The build then fails:

```
$ go version
go version go1.12.7 darwin/amd64

$ spago build -- -g corefn && psgo 
Installation complete.
Build succeeded.
can't load package: package Main: unknown import path "Main": cannot find module providing package Main
```

Running `go build` myself also fails:

```
$ spago build -- -g corefn && psgo --no-build
Installation complete.
Build succeeded.

$ cd output/src/Main; go build .
build github.com/pmahoney/example/output/src/Main: cannot load Effect_Console: cannot find module providing package Effect_Console
```

In general, I'm not sure un-namespaced imports are possible when using go modules (other than from the go standard library), where previously constructing an appropriate GOPATH allowed this. `go help gopath` says:

> When using modules, GOPATH is no longer used for resolving imports.

**Comment by andyarvanitis** [comment]
I haven't done anything with go modules yet. From what I had read, I believe you are right that the generated imports will need to include the module name. I anticipate having a switch on `psgo` to enable/disable use of modules.

**Comment by andyarvanitis** [comment]
I've been looking into modules now, and believe I have something working the way I'd like, although it might still need some tweaking. If you are pretty familiar/comfortable with go modules, you can try building `psgo` out of the `golang-modules` branch. If not, you can wait until I release it and provide instructions. However, the main "quick start" difference is that you don't need to manually clone `purescript-native-go-ffi` anymore.

Based on what I've been reading, I'm not sure I'll support both a `GOPATH` and modules mode, but I'll continue to give it some thought.

**Comment by andyarvanitis** [comment]
The latest version of `psgo` now uses Golang modules instead of GOPATH: 57f696b3d8922910bce8eba9ea706c2f387c4876 and (release 2019-08-12).

**Comment by pmahoney** [comment]
That's great @andyarvanitis , can't wait to get a chance to try it out.

**Comment by andyarvanitis** [comment]
Great, thanks. I'll leave this open until at least you've had a chance to try it. I also need to add some documentation on how to do custom FFI.

**Comment by pmahoney** [comment]
Successfully built a "hello world"!

I did have to include two `replace` directives in my toplevel `go.mod`:

```
module github.com/pmahoney/example

replace purescript-native/output => ./output

replace purescript-native/ffi-loader => ./purescript-native
```

Is that expected? Seems reasonable enough.

Thanks, this is great; looking forward to doing something beyond "hello world"!

**Comment by andyarvanitis** [comment]
Great! It is (sort of) expected – if you didn't already have a go.mod file
in your working directory, psgo would have generated one for you with those
replace directives.

**Comment by andyarvanitis** [comment]
I made it a little more robust now. If you had already created a `go.mod` in your working directory, it will still add those `replace` directives (it now uses `go mod edit` commands). The latest code in branch `golang` has this change, but I haven't updated the prebuilt binaries yet.

**Comment by andyarvanitis** [comment]
2019-09-02 prebuilt binaries have this fix, so closing
