### ISSUE TITLE
A few issues on a sample project

### ISSUE THREAD

**Issue by drewolson** [andyarvanitis/purescript-native#44]
First and foremost, thanks for purescript-native! I'm super excited about the potential of using a go backend for PureScript.

I recently created a small example project [here](https://github.com/drewolson/purs-native-example) and noticed a few interesting things.

First, the generated `replace` directives in the top-level `go.mod` used absolute paths. This seems bad. I [replaced them](https://github.com/drewolson/purs-native-example/blob/2fbf53e2f6560ff3ca3e8d977107188047e09580/go.mod#L3-L5) with relative paths and everything continues to build. I believe this should be the default behavior. Thoughts?

Second, when creating my foreign implementation for `foreign import myEffect :: Effect Int`, I expected to be able to export a `func () int`. This successfully builds, but segfaults at runtime. It seems I need to return a `func () Any`, even though my `Effect` is parameterized by `Int`. You can see the implementations [here](https://github.com/drewolson/purs-native-example/blob/2fbf53e2f6560ff3ca3e8d977107188047e09580/purescript-native/example/Main.go#L10-L16).

Last, it feels a little strange to have so many levels of `go.mod` files and have the default naming scheme for the project be `project.localhost/purescript-native/ffi-loader`. I ended up creating a new package within the `purescript-native` directory and importing it in the `ffi-loader` [here](https://github.com/drewolson/purs-native-example/blob/2fbf53e2f6560ff3ca3e8d977107188047e09580/purescript-native/ffi_loader.go#L30-L32), but this feels strange. Is this the idiomatic way to introduce my own foreign functions?

Thanks!

**Comment by andyarvanitis** [comment]
1) Since the `go.mod` is generated for the project, I'm fine with either absolute or relative paths, though I'm not sure how well relative are supported by the Go tools.

1) Yes, all types need to be `Any`, and all functions curried.

1) Not sure there is anything idiomatic yet, so you can put them wherever you like. However, I would probably avoid directories that are generated by the tools, since you might want to wipe them and regen sometimes.

**Comment by drewolson** [comment]
Thanks! Would you accept a PR updating the top-level replace directives to use relative paths?

**Comment by drewolson** [comment]
Add added a PR to update to relative paths. It's here https://github.com/andyarvanitis/purescript-native/pull/46.

Please merge if you're interested. Thanks!

**Comment by andyarvanitis** [comment]
Sure, I'd be happy to. I did a quick search, and it looks like relative paths are supported:

https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive

As for your PR, did you happen to test it on Windows? I generally try to make sure things work on macOS (my primary dev env), *nix, and Windows, though I don't assume everyone who submits a PR does that.
