### ISSUE TITLE
Extending existing go FFI bindings

### ISSUE THREAD

**Issue by drewolson** [andyarvanitis/purescript-native#48]
I've created a [project](https://github.com/drewolson/purescript-native-ffi) to demonstrate an issue I'm experiencing. I noticed that the [existing FFI](https://github.com/andyarvanitis/purescript-native-go-ffi/blob/668e704c064dae4066cff3508bbd3530fdde42d7/purescript-effect/Effect_Uncurried.go#L10) implementation for `Effect.Uncurried` doesn't implement `runEffectFn2`, so I decided to add it myself.

If I add the required code to one of [my own modules](https://github.com/drewolson/purescript-native-ffi/blob/c7c499cde89e80ec21b42af1e461143f3d86280e/ffi/Main.go#L23-L33) (e.g. `Main`), it works [fine](https://github.com/drewolson/purescript-native-ffi/blob/c7c499cde89e80ec21b42af1e461143f3d86280e/src/Main.purs#L21-L23). However, if I attempt to extend the existing FFI implementations for the `Effect.Uncurried` module in [my own code](https://github.com/drewolson/purescript-native-ffi/blob/c7c499cde89e80ec21b42af1e461143f3d86280e/ffi/Effect_Uncurried.go#L10-L20), it [fails](https://github.com/drewolson/purescript-native-ffi/blob/c7c499cde89e80ec21b42af1e461143f3d86280e/src/Main.purs#L25-L27) with a segfault. Based on my reading of the [Foreign](https://github.com/purescript-native/go-runtime/blob/832294f92e57ab423bdf344bd303007e33c5cefe/purescript.go#L28-L35) function, it seems that I should be able to extend bindings for existing modules.

What am I doing wrong?

**Comment by andyarvanitis** [comment]
Your understanding and implementation look correct, but I'm pretty sure `Effect.Uncurried.runEffectFn2` is never called due to the [inliner](https://github.com/andyarvanitis/purescript-native/blob/golang/src/CodeGen/IL/Optimizer/Inliner.hs); which means that there might be a bug in it somewhere.

**Comment by andyarvanitis** [comment]
Sorry I took so long to get back to this. It is indeed the inliner at fault. If disabled, your code works fine. I have a fix for it, but I need to test it a bit more before releasing.

**Comment by drewolson** [comment]
Nice to hear you’ve found this issue! I’m glad to see work continuing on this exciting project.
