### ISSUE TITLE
Incorrect equality check in Data_Interval_Duration_Iso

### ISSUE THREAD

**Issue by mikesol** [andyarvanitis/purescript-native#58]
The following cpp code was generated for boxed variables:

```cpp
            return Math::floor()(a) != a;
```

I'm still learning how all this is put together, but it seems the correct generation would be:

```cpp
            return Data_Eq::notEq()(Math::floor()(a))(a);
```

**Comment by andyarvanitis** [comment]
Like the other report, that's due to the inliner. Direct floating point comparisons are never really a good idea, though – I removed them from the golang backend, and should do the same for the C++ one. But was there a bug here, or is it just a question about the codegen?

**Comment by mikesol** [comment]
It's a bug, apologies for the ambiguity.  It did not compile unless I changed it to `return Data_Eq::notEq()(Math::floor()(a))(a);`.

**Comment by andyarvanitis** [comment]
Ah ok, interesting. At a glance, I don't know why that isn't working. I'll likely go ahead and disable the inliner for `Number` ([this](https://github.com/purescript-native/cpp-ffi/blob/268567879eed9a1da8450f07277382a76c658a90/prelude/data-eq.cpp#L23) is already there), but I'll have a look as to why first.
