### ISSUE TITLE
stack nix integration

### ISSUE THREAD

**Issue by joprice** [andyarvanitis/purescript-native#68]
I was getting linker errors on ubuntu trying to stack instal psgo, as it was failing to find gmp. I noticed that gmp was already listed in the stack.nix file, so it should be picked up. I finally realized that the "enable" flag is missing under nix so the nix integration in stack is not actually active:

```yaml
 nix:
+  enable: true
   shell-file: stack.nix
 ```

After enabling this, it built flawlessly. If you're not using this personally, I think it would at least be helpful to put this line in there, commented out with a comment above suggesting to uncomment if you'd like to use nix to build.

**Comment by andyarvanitis** [comment]
Unfortunately I've never used nix, the support we have is from contributors. Happy to merge a PR if you end up making one, though.
