### ISSUE TITLE
Update to PureScript 0.14

### ISSUE THREAD

**Issue by i-am-the-slime** [andyarvanitis/purescript-native#75]
I suppose this is quite an obvious ticket. It would be very nice if purescript-native would work with the latest version of the compiler.

**Comment by andyarvanitis** [comment]
Thanks, always good to track. BTW, are you actively using it?

**Comment by i-am-the-slime** [comment]
Hey, I'm using it on- and off. Not sure what the threshold for actively using really is 😁 .

**Comment by i-am-the-slime** [comment]
@andyarvanitis Is it possible that it just works™? That'd be the case if the corefn representation hasn't changed, right?

**Comment by andyarvanitis** [comment]
Yes exactly, and I think there’s a good chance that it hasn’t.

**Comment by i-am-the-slime** [comment]
At least for me it does! I'll close this!
