### ISSUE TITLE
Missing FFI implementation only reported on first invocation of pcc

### ISSUE THREAD

**Issue by kasbah** [andyarvanitis/purescript-native#8]
Hey, just trying to get a hello world example compiled. New to Purescript and Pure14 so I apologise for my ignorance in advance. 

The code I am trying to compile is the hello world from pulp with modified [bower.json](https://github.com/kasbah/pure14-hello/blob/master/bower.json) and using a [Makefile](https://github.com/kasbah/pure14-hello/blob/master/Makefile).

Currently I get this error on the first invocation of make

```
Missing FFI implementations for module Prelude
```

on the second invocation, make completes without reporting any errors but if I go through using cmake and then using the generated makefile it reports:

```
Prelude.hh:6:26: fatal error: Prelude_ffi.hh: No such file or directory
 #include "Prelude_ffi.hh"
```

and I can't find this file in the output either.

**Comment by andyarvanitis** [comment]
For some libraries (including Prelude), you need to use the version from the [pure14 org](https://github.com/pure14). See [this list](https://github.com/andyarvanitis/pure14/wiki/Packages).

Also, there's a sample [Makefile](https://github.com/andyarvanitis/pure14/blob/pure14-master/pcc/Makefile.example) that you can use for the PureScript -> C++ compilation. 

Sorry, there's not much helpful documentation yet, as I've spent most of my time so far just working on the compiler itself. I hope to do it soon, but let me know if you run into anything else.

**Comment by andyarvanitis** [comment]
Oh, sorry, I just saw your modified bower file that's already pointing to the pure14 versions.
I also see that you got to the cmake stage. Are you sure it's using the right package?

**Comment by andyarvanitis** [comment]
To clarify: please make sure the right version of prelude got pulled in by bower. I don't really use bower right now, I just pull things in directly via git. The right version will have a `Prelude.hh` file in the same directory as `Prelude.js`.

**Comment by kasbah** [comment]
Thanks for taking a look. You were right, bower was checking out the 0.1.0 tag of prelude which didn't have the `Prelude.hh`. [Fixed it](https://github.com/kasbah/pure14-hello/commit/c1d5a37a5e528f344b84886592e462d4abdcdcb5). Not much of a bower user myself either. 

I guess the only actual bug here is that `pcc` doesn't report an error on the second try. 

What compiler do you recommend by the way? I am now running into some C++ compilation issues (using gcc 4.9.2).

**Comment by andyarvanitis** [comment]
Ok cool. Definitely a recent version of clang, meaning 3.5.x or 3.6.x. I think 3.4.2 might be ok too, but earlier than that wants `-std=c++1y` instead of `-std=c++14` (I think it's fine other than that).

`gcc 5.1` might also be ok, but I haven't tried it in a while, so something might not work anymore. If you try it and it does work, please let me know, though. I mostly work on a Mac, but with clang I've seen everything working fine on Linux and FreeBSD.

**Comment by kasbah** [comment]
Clang 3.6.0 and gcc 5.1.0 are both working well for me for the hello world at least (I am on Ubuntu 14.04).

**Comment by andyarvanitis** [comment]
Great! In case you haven't seen it, this shows some of the things that are and are not currently working: https://github.com/andyarvanitis/pure14/blob/pure14-master/pcc/TestMain.hs

**Comment by andyarvanitis** [comment]
No longer applicable due to new approach.
